typography_spectrum: 0.16592377028428018
color:
  brandStrength: 0.39159788959659636
  lightness: 0.34670778131112456
  saturation: 0.01761054527014494
  rhythmicContrast: 0.5792132180649787
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.20240339310839772
author:
  name: COCAP I/S
  email: mail@cocap.dk
  url: 'http://cocap.dk'
name: COCAP
navigation:
  - name: Morten Pradsgaard
    url: 'http://mopra.dk'
    type: external
  - name: Anders Ladegaard
    url: 'http://anders-ladegaard.dk/'
    type: external
title: COCAP
description: Sæt skub i dit foretagende!
