typography_spectrum: 0.8545711415354162
color:
  brandStrength: 0.9030300804879516
  lightness: 0.5980204481165856
  saturation: 0.3182966485619545
  rhythmicContrast: 0.8084846725687385
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.12106626271270216
author:
  name: COCAP I/S
  email: mail@cocap.dk
  url: 'http://cocap.dk'
name: COCAP
navigation:
  - name: mopradk
    url: 'http://mopra.dk'
    type: external
  - name: Anders Ladegaard
    url: 'http://anders-ladegaard.dk/'
    type: external
title: COCAP
description: Sæt skub i dit foretagende!
